import os
import requests


def create_vinyl_product(song_title: str, lyrics: str, genre: str, mood: str, bpm: int, key: str, audio_url: str = "") -> dict:
    """Create a vinyl record product on Shopify via Admin API."""
    admin_token = os.getenv("SHOPIFY_ADMIN_TOKEN")
    domain = os.getenv("NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN")

    if not admin_token or not domain:
        return {"error": "Shopify Admin API not configured"}

    url = f"https://{domain}/admin/api/2024-01/products.json"

    description = f"""<p><strong>{song_title}</strong> — a one-of-a-kind vinyl record generated by MemoMuse AI.</p>
<p><strong>Genre:</strong> {genre}<br>
<strong>Mood:</strong> {mood}<br>
<strong>BPM:</strong> {bpm}<br>
<strong>Key:</strong> {key}</p>
<h3>Lyrics</h3>
<pre>{lyrics}</pre>
<p><em>Each vinyl is custom pressed with your AI-generated track. Ships in 2-3 weeks.</em></p>"""

    product_data = {
        "product": {
            "title": f"{song_title} — MemoMuse Vinyl",
            "body_html": description,
            "vendor": "MemoMuse",
            "product_type": "Vinyl Record",
            "status": "active",
            "published": True,
            "tags": f"memomuse, ai-generated, {genre.lower()}, vinyl",
            "variants": [
                {
                    "price": "24.99",
                    "sku": f"MM-VINYL-{hash(song_title) % 99999:05d}",
                    "inventory_quantity": 100,
                    "requires_shipping": True,
                }
            ],
        }
    }

    headers = {
        "X-Shopify-Access-Token": admin_token,
        "Content-Type": "application/json",
    }

    response = requests.post(url, json=product_data, headers=headers, timeout=15)

    if response.status_code in (200, 201):
        product = response.json().get("product", {})
        product_id = product.get("id")
        handle = product.get("handle", "")
        return {
            "product_id": product_id,
            "product_url": f"https://{domain}/products/{handle}",
            "handle": handle,
        }

    return {"error": f"Shopify API error {response.status_code}: {response.text[:200]}"}
